CREATE TABLE IF NOT EXISTS portfolio_items (
  stock_code VARCHAR(6) NOT NULL,
  stock_name VARCHAR(120) NOT NULL,
  group_label VARCHAR(80) NULL,
  rate DOUBLE NULL,
  mention_count BIGINT NULL,
  weight DOUBLE NOT NULL DEFAULT 10,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (stock_code)
);
