export const COPY = {
  brand: "한국 주식 AI 리서치",
  productTagline: "차트, AI 근거, 쉬운 용어로 배우는 한국 주식 리서치",
  todayBrief: "오늘의 시장 브리프",
  heroTitle: "AI가 오늘 한국 주식 흐름을 차트와 근거로 정리합니다",
  heroSubtitle: "검색하거나, 차트를 보거나, AI에게 물어보면 됩니다. 초보자도 오늘 시장의 이유와 리스크를 한 화면에서 확인합니다.",
  marketBrief: "시장 브리프",
  marketOneLine: "오늘 시장에서 눈에 띄는 종목과 확인할 근거를 먼저 보여줍니다.",
  noMarketOneLine: "아직 저장된 브리프가 없습니다. 최신 요약을 불러오거나 운영 담당자가 생성한 뒤 확인할 수 있습니다.",
  universalSearch: "산업, 테마, 기업, 종목 검색",
  universalSearchPlaceholder: "예: 반도체, 007610, 선도전기, 거래량, DART",
  searchEmpty: "검색 결과가 없습니다. 종목명, 코드, 산업, 테마, 용어를 바꿔 입력해 보세요.",
  aiMarketPanel: "AI 시장 해석",
  aiMarketOneLine: "AI가 오늘 움직인 종목, 차트 신호, 리스크를 한 흐름으로 설명합니다.",
  aiInsight: "AI 인사이트",
  dataAsOf: "데이터 기준일",
  sourceConfidence: "신뢰도",
  beginnerSignals: "초보자가 지금 확인할 신호",
  chartLoading: "차트 불러오는 중...",
  chartFailed: "차트 데이터를 불러오지 못했습니다.",
  riskMode: "판단 성향",
  aggressive: "공격형",
  neutral: "중립형",
  conservative: "보수형",
  chartSummary: "현재 차트 상태 요약",
  buyConditions: "매수 검토 조건",
  splitBuyConditions: "분할매수 검토 조건",
  watchConditions: "관망 조건",
  sellConditions: "매도 검토 조건",
  stopConditions: "손절/리스크 관리 조건",
  oppositeSignals: "반대 신호",
  evidenceData: "근거 데이터",
  analysisDisclaimer: "교육용 분석 보조 정보이며 매수, 매도 지시나 수익 보장이 아닙니다.",
  askChartAi: "AI로 차트 설명",
  aiResearchTitle: "AI 차트 해석",
  portfolioTitle: "포트폴리오 샌드박스",
  portfolioSubtitle: "실계좌 연동 없이 관심 종목과 가상 비중으로 리스크를 봅니다.",
  addToPortfolio: "관심 추가",
  virtualWeight: "가상 비중",
  concentration: "집중도",
  volatility: "변동성",
  openAdmin: "관리자 영역",
  closeAdmin: "관리자 영역 닫기",
  adminTitle: "운영 관리",
  adminSubtitle: "생성, 보관, 일괄 생성은 접힌 패널에서만 실행합니다.",
  selectedDate: "조회 기준일",
  generateToday: "오늘 생성",
  moveToLatest: "최신 요약",
  toggleDarkOn: "다크 모드",
  toggleDarkOff: "라이트 모드",
  prevMonth: "이전",
  nextMonth: "다음",
  generateSelected: "선택일 생성",
  archiveSelected: "보관",
  backfillRun: "일괄 생성",
  loading: "불러오는 중...",
  noSummary: "이 날짜의 요약이 아직 없습니다.",
  marketClosed: "휴장일",
  marketClosedDesc: "이 날짜는 증권시장 휴장일입니다.",
  generatedAt: "생성 시각",
  topGainer: "최대 상승",
  topLoser: "최대 하락",
  mostMentioned: "최다 언급",
  kospiPick: "코스피 픽",
  kosdaqPick: "코스닥 픽",
  rankingBasis: "랭킹 계산 근거",
  rawFirstGainer: "처음 계산 1위 (상승)",
  rawFirstLoser: "처음 계산 1위 (하락)",
  filteredFirstGainer: "검토 후 1위 (상승, 최종)",
  filteredFirstLoser: "검토 후 1위 (하락, 최종)",
  warningNote: "주의 메모",
  code: "종목코드",
  name: "종목명",
  rate: "등락률(%)",
  signals: "감지 신호",
  description: "설명",
  evidenceLinks: "근거 링크",
  verification: "검증",
  date: "날짜",
  result: "결과값",
  directLink: "바로 확인",
  notes: "주의사항",
  showRawNotes: "수집 노트 보기",
  developerDetails: "검증 상세",
  summaryExists: "요약 있음",
  gatedHint: "이 화면은 비밀키가 필요합니다. URL에 ?k=비밀키 를 추가하세요.",
  cumulativeSummaries: "누적 요약",
  latestDate: "최신 날짜",
  lastUpdated: "최근 갱신",
  monthlyTotalDays: "월 총 일수",
  monthlyGenerated: "생성 완료",
  monthlyMissing: "미생성",
  monthlyTopMentioned: "월 최다 언급",
  days: ["일", "월", "화", "수", "목", "금", "토"],
  verifyField: "항목",
  verifySource: "출처",
  krxArtifact: "KRX 검증",
  krxPortal: "KRX 포털",
  pykrxRepo: "pykrx 저장소",
  actualCalcDate: "실제 계산일",
  topGainersTitle: "상승 TOP3",
  topLosersTitle: "하락 TOP3",
  mostMentionedTitle: "언급 TOP3",
  postCount: "게시물 수",
  naverDaily: "일별",
  naverMain: "종합",
  naverBoard: "토론",
  learningTitle: "초보자 용어 사전",
  learningSubtitle: "브리프를 읽을 때 막히는 단어를 바로 풀어봅니다.",
  learningSearch: "용어 검색",
  learningSearchPlaceholder: "예: 등락률, PER, 거래량",
  allCategories: "전체",
  coreSummary: "핵심요약",
  longExplanation: "자세한 설명",
  chartUsage: "차트에서 보는 법",
  whyItMatters: "왜 중요한가",
  beginnerCheck: "먼저 확인할 것",
  caution: "오해하기 쉬운 점",
  scenarioExample: "시나리오 예시",
  relatedTerms: "관련 용어",
  exampleQuestions: "바로 물어보기",
  learningLoadFailed: "용어 사전을 불러오지 못했습니다.",
  noTerms: "검색 결과가 없습니다.",
  assistantTitle: "AI 학습 도우미",
  assistantSubtitle: "오늘 브리프와 용어 사전을 묶어 초보자 관점으로 설명합니다.",
  assistantQuestionLabel: "AI에게 물어볼 질문",
  assistantInputPlaceholder: "궁금한 점을 입력하세요. 예: 거래량이 왜 중요해?",
  assistantAsk: "질문",
  assistantAnswer: "답변",
  confidence: "신뢰도",
  sources: "출처",
  limitations: "한계",
  matchedTerms: "연결된 용어",
  briefTermsTitle: "브리프 읽기 전 확인할 용어",
  historyTitle: "히스토리",
  adminKeyRequired: "운영 기능은 관리자 키가 필요합니다. URL에 ?ak=관리자키 를 추가하면 생성, 보관, 일괄 생성을 사용할 수 있습니다."
};

export const PAGE_LABELS = {
  home: "리서치",
  research: "차트 AI",
  history: "기록",
  learning: "배우기",
  portfolio: "포트폴리오",
  admin: "운영"
};

export const SEARCH_STOCK_FALLBACKS = [
  {
    id: "stock-005930-baseline",
    type: "stock",
    title: "삼성전자",
    code: "005930",
    market: "KOSPI",
    rate: "대표",
    tags: ["반도체", "AI 반도체", "메모리", "대형주", "코스피"],
    summary: "한국 반도체와 대형주 흐름을 볼 때 가장 먼저 확인하는 대표 종목입니다.",
    stock: { code: "005930", name: "삼성전자", group: "반도체 대표 종목" }
  },
  {
    id: "stock-000660-baseline",
    type: "stock",
    title: "SK하이닉스",
    code: "000660",
    market: "KOSPI",
    rate: "대표",
    tags: ["반도체", "HBM", "메모리", "AI 반도체", "코스피"],
    summary: "HBM, 메모리 가격, AI 서버 투자 흐름과 연결해 보는 반도체 대표 종목입니다.",
    stock: { code: "000660", name: "SK하이닉스", group: "반도체 대표 종목" }
  },
  {
    id: "stock-005380-baseline",
    type: "stock",
    title: "현대차",
    code: "005380",
    market: "KOSPI",
    rate: "대표",
    tags: ["자동차", "전기차", "수출", "환율", "코스피"],
    summary: "자동차 수출, 환율, 전기차 전환을 함께 확인하는 대표 완성차 종목입니다.",
    stock: { code: "005380", name: "현대차", group: "자동차 대표 종목" }
  },
  {
    id: "stock-035420-baseline",
    type: "stock",
    title: "NAVER",
    code: "035420",
    market: "KOSPI",
    rate: "대표",
    tags: ["네이버", "인터넷", "플랫폼", "AI", "광고"],
    summary: "광고, 커머스, AI 서비스 기대를 함께 보는 대표 인터넷 플랫폼 종목입니다.",
    stock: { code: "035420", name: "NAVER", group: "플랫폼 대표 종목" }
  },
  {
    id: "stock-035720-baseline",
    type: "stock",
    title: "카카오",
    code: "035720",
    market: "KOSPI",
    rate: "대표",
    tags: ["카카오", "인터넷", "플랫폼", "콘텐츠", "핀테크"],
    summary: "플랫폼, 콘텐츠, 핀테크 이슈가 함께 움직이는 대표 인터넷 종목입니다.",
    stock: { code: "035720", name: "카카오", group: "플랫폼 대표 종목" }
  }
];

export const SEARCH_THEME_FALLBACKS = [
  {
    id: "theme-semiconductor",
    type: "theme",
    title: "반도체",
    code: "THEME",
    market: "테마",
    rate: "+2.4%",
    tags: ["AI 반도체", "HBM", "메모리", "장비"],
    summary: "AI 서버 투자, 메모리 가격, 장비 수주, 환율을 함께 보는 대표 성장 테마입니다."
  },
  {
    id: "theme-battery",
    type: "theme",
    title: "2차전지",
    code: "THEME",
    market: "테마",
    rate: "-1.1%",
    tags: ["배터리", "양극재", "전기차", "리튬"],
    summary: "원재료 가격, 전기차 수요, 정책 뉴스가 주가 변동과 자주 연결됩니다."
  },
  {
    id: "theme-ai",
    type: "theme",
    title: "AI",
    code: "THEME",
    market: "테마",
    rate: "+1.8%",
    tags: ["반도체", "클라우드", "로봇", "데이터센터"],
    summary: "AI 인프라 투자와 소프트웨어 기대가 반도체, 인터넷, 로봇 종목으로 확산되는지 확인합니다."
  },
  {
    id: "theme-bio",
    type: "theme",
    title: "바이오",
    code: "THEME",
    market: "테마",
    rate: "+0.6%",
    tags: ["CDMO", "신약", "임상", "바이오시밀러"],
    summary: "임상, 허가, 기술수출, 실적 가시성이 동시에 투자심리를 흔드는 고변동 테마입니다."
  },
  {
    id: "theme-defense",
    type: "theme",
    title: "방산",
    code: "THEME",
    market: "테마",
    rate: "+1.4%",
    tags: ["수출", "항공우주", "국방", "정책"],
    summary: "수출 계약, 지정학 이슈, 정부 예산, 환율이 실적 기대와 함께 움직입니다."
  },
  {
    id: "theme-robot",
    type: "theme",
    title: "로봇",
    code: "THEME",
    market: "테마",
    rate: "+1.2%",
    tags: ["자동화", "협동로봇", "AI", "스마트팩토리"],
    summary: "제조 자동화와 AI 적용 기대가 커질 때 관심이 모이는 성장 테마입니다."
  },
  {
    id: "theme-shipbuilding",
    type: "theme",
    title: "조선",
    code: "THEME",
    market: "테마",
    rate: "+0.7%",
    tags: ["LNG선", "수주", "해양플랜트", "환율"],
    summary: "선가, 수주잔고, 원가, 환율이 함께 움직이는 경기민감 산업 테마입니다."
  },
  {
    id: "industry-finance",
    type: "industry",
    title: "증권/금융",
    code: "IND",
    market: "산업",
    rate: "+0.8%",
    tags: ["은행", "증권", "금리", "배당"],
    summary: "금리, 충당금, 배당, 증시 거래대금이 이익과 밸류에이션에 직접 연결됩니다."
  },
  {
    id: "industry-auto",
    type: "industry",
    title: "자동차",
    code: "IND",
    market: "산업",
    rate: "+0.8%",
    tags: ["완성차", "전기차", "부품", "환율"],
    summary: "판매량, 인센티브, 환율, 전기차 전환 속도를 함께 보는 대표 수출 산업입니다."
  },
  {
    id: "industry-internet",
    type: "industry",
    title: "인터넷/플랫폼",
    code: "IND",
    market: "산업",
    rate: "+0.3%",
    tags: ["AI", "광고", "커머스", "콘텐츠"],
    summary: "광고 경기, 커머스 성장, AI 서비스, 규제 이슈를 함께 확인합니다."
  }
];

const makeTerm = ({
  id,
  term,
  category,
  coreSummary,
  plainDefinition,
  chartUsage,
  whyItMatters,
  beginnerCheck,
  commonMisunderstanding,
  scenario,
  relatedTerms = [],
  exampleQuestions = []
}) => ({
  id,
  term,
  category,
  coreSummary,
  plainDefinition,
  longExplanation: `${plainDefinition}\n차트나 재무 화면에서 숫자 하나만 보지 말고 같은 업종, 전일 흐름, 거래량을 함께 봐야 합니다.\n초보자는 이 용어를 행동 지시가 아니라 확인 순서를 정하는 기준으로 쓰는 편이 안전합니다.`,
  chartUsage,
  whyItMatters,
  beginnerCheck,
  caution: commonMisunderstanding,
  commonMisunderstanding,
  scenario,
  relatedTerms,
  exampleQuestions
});

export const LEARNING_TERM_FALLBACKS = [
  makeTerm({
    id: "price-change-rate",
    term: "등락률",
    category: "시장",
    coreSummary: "전일 종가 대비 오늘 가격이 얼마나 움직였는지 보여주는 비율입니다.",
    plainDefinition: "등락률은 주가가 전날 끝난 가격보다 몇 퍼센트 오르거나 내렸는지 나타냅니다.",
    chartUsage: "종가 옆 퍼센트, 일봉의 색, 검색 결과의 +/− 숫자로 확인합니다.",
    whyItMatters: "오늘 시장에서 관심이 어디에 몰렸는지 빠르게 고를 때 출발점이 됩니다.",
    beginnerCheck: "등락률이 크면 거래량, 공시, 뉴스가 같이 있는지 먼저 확인합니다.",
    commonMisunderstanding: "많이 올랐다고 좋은 종목, 많이 내렸다고 싼 종목이라고 단정하면 안 됩니다.",
    scenario: "예: +12% 급등 종목은 바로 추격하기보다 거래량 지속, 윗꼬리, 다음 지지선을 확인합니다.",
    relatedTerms: ["거래량", "일봉", "변동성"],
    exampleQuestions: ["등락률이 큰 종목은 무엇부터 확인해야 해?", "급등 종목을 추격하면 왜 위험해?"]
  }),
  makeTerm({
    id: "volume",
    term: "거래량",
    category: "차트",
    coreSummary: "하루 동안 실제로 사고팔린 주식 수입니다.",
    plainDefinition: "거래량은 투자자 참여가 얼마나 강했는지 보여주는 기본 지표입니다.",
    chartUsage: "캔들 아래 막대 그래프로 보며, 평소보다 크게 튄 막대를 찾습니다.",
    whyItMatters: "가격 움직임이 실제 관심을 동반했는지 판단하는 핵심 근거입니다.",
    beginnerCheck: "가격 상승과 거래량 증가가 함께 나오는지, 급등 뒤 거래량이 꺼지는지 봅니다.",
    commonMisunderstanding: "거래량이 많다고 항상 상승 신호는 아닙니다. 하락 거래량도 강한 경고일 수 있습니다.",
    scenario: "예: 돌파일 거래량이 20일 평균의 2배라면 관심 후보, 다음 날 급감하면 관망으로 바꿉니다.",
    relatedTerms: ["거래대금", "OBV", "돌파"],
    exampleQuestions: ["거래량이 늘었는데 주가가 내리면 어떻게 봐?", "평균 거래량은 왜 봐?"]
  }),
  makeTerm({
    id: "trading-value",
    term: "거래대금",
    category: "시장",
    coreSummary: "거래량에 가격을 곱한 실제 돈의 규모입니다.",
    plainDefinition: "거래대금은 시장에서 얼마만큼의 자금이 오갔는지 보여줍니다.",
    chartUsage: "종목 랭킹, 거래대금 상위, 시장 관심 후보 목록에서 확인합니다.",
    whyItMatters: "소형주 착시를 줄이고 실제 자금 유입 종목을 고르는 데 도움됩니다.",
    beginnerCheck: "등락률만 보지 말고 거래대금이 충분한지 같이 봅니다.",
    commonMisunderstanding: "거래량이 많아도 가격이 너무 낮으면 실제 자금 규모는 작을 수 있습니다.",
    scenario: "예: 거래대금 상위에 처음 오른 종목은 공시, 뉴스, 수급이 동반됐는지 확인합니다.",
    relatedTerms: ["거래량", "시가총액", "수급"],
    exampleQuestions: ["거래량과 거래대금은 뭐가 달라?", "거래대금 상위는 왜 중요해?"]
  }),
  makeTerm({
    id: "per",
    term: "PER",
    category: "재무",
    coreSummary: "주가가 이익 대비 몇 배로 평가되는지 보는 지표입니다.",
    plainDefinition: "PER은 시가총액을 순이익으로 나눈 값으로, 이익 대비 가격 부담을 봅니다.",
    chartUsage: "차트보다는 종목 재무/밸류에이션 영역에서 업종 평균과 비교합니다.",
    whyItMatters: "성장 기대와 가격 부담이 균형인지 판단하는 출발점입니다.",
    beginnerCheck: "같은 업종 평균, 일회성 이익, 적자 여부를 함께 확인합니다.",
    commonMisunderstanding: "PER이 낮다고 무조건 싸고, 높다고 무조건 비싼 것은 아닙니다.",
    scenario: "예: PER이 낮아도 이익이 줄어드는 업종이면 저평가가 아니라 실적 둔화일 수 있습니다.",
    relatedTerms: ["PBR", "ROE", "시가총액"],
    exampleQuestions: ["PER이 낮은 종목을 바로 사면 안 되는 이유는?", "PER은 업종별로 왜 달라?"]
  }),
  makeTerm({
    id: "pbr",
    term: "PBR",
    category: "재무",
    coreSummary: "주가가 회사 순자산 대비 몇 배인지 보는 지표입니다.",
    plainDefinition: "PBR은 시가총액을 자기자본으로 나눠 자산 대비 가격 수준을 확인합니다.",
    chartUsage: "차트보다는 재무 비교에서 저PBR, 자산주, 금융주 판단에 자주 씁니다.",
    whyItMatters: "자산 가치 대비 과도하게 싸거나 비싼지 가늠하는 데 도움됩니다.",
    beginnerCheck: "ROE가 낮은 저PBR은 오래 저평가될 수 있으니 수익성도 같이 봅니다.",
    commonMisunderstanding: "PBR 1배 아래가 항상 매수 기회라는 뜻은 아닙니다.",
    scenario: "예: 저PBR 은행주는 배당, 충당금, 금리 방향을 함께 확인한 뒤 비교합니다.",
    relatedTerms: ["PER", "ROE", "배당"],
    exampleQuestions: ["PBR 1배는 무슨 의미야?", "저PBR 종목은 왜 계속 싸게 남아?"]
  }),
  makeTerm({
    id: "roe",
    term: "ROE",
    category: "재무",
    coreSummary: "회사가 자기자본으로 이익을 얼마나 잘 냈는지 보는 수익성 지표입니다.",
    plainDefinition: "ROE는 순이익을 자기자본으로 나눈 값입니다.",
    chartUsage: "재무 요약에서 PER, PBR과 함께 비교해 밸류에이션의 질을 봅니다.",
    whyItMatters: "높은 ROE는 같은 자본으로 더 많은 이익을 내는 기업일 가능성을 보여줍니다.",
    beginnerCheck: "일회성 이익 때문에 ROE가 높아졌는지 확인합니다.",
    commonMisunderstanding: "ROE가 높아도 부채가 과도하면 리스크가 커질 수 있습니다.",
    scenario: "예: PBR이 높아도 ROE가 꾸준히 높으면 프리미엄을 일부 설명할 수 있습니다.",
    relatedTerms: ["PER", "PBR", "부채비율"],
    exampleQuestions: ["ROE가 높은 기업은 항상 좋은 기업이야?", "ROE와 PBR은 같이 어떻게 봐?"]
  }),
  makeTerm({
    id: "disclosure",
    term: "공시",
    category: "공시/뉴스",
    coreSummary: "회사가 투자자에게 공식적으로 알리는 중요 정보입니다.",
    plainDefinition: "공시는 실적, 계약, 유상증자, 최대주주 변경 같은 기업 정보를 공식 채널에 공개하는 것입니다.",
    chartUsage: "차트 이벤트 마커, 급등락 당일 근거 링크, DART 원문에서 확인합니다.",
    whyItMatters: "가격 변화의 원인이 소문인지 공식 정보인지 구분하는 핵심 근거입니다.",
    beginnerCheck: "제목만 보지 말고 금액, 기간, 조건, 정정 여부를 확인합니다.",
    commonMisunderstanding: "좋아 보이는 공시도 이미 주가에 반영됐거나 조건이 약할 수 있습니다.",
    scenario: "예: 공급계약 공시는 계약금액이 매출 대비 큰지 보고 차트 거래량 반응을 확인합니다.",
    relatedTerms: ["DART", "거래량", "수급"],
    exampleQuestions: ["공시 원문에서 무엇부터 봐야 해?", "호재 공시인데 주가가 왜 내려?"]
  }),
  makeTerm({
    id: "dart",
    term: "DART",
    category: "공시/뉴스",
    coreSummary: "금융감독원 전자공시시스템입니다.",
    plainDefinition: "DART는 상장사가 제출한 공식 공시 문서를 확인하는 사이트입니다.",
    chartUsage: "차트의 공시 마커나 근거 링크에서 원문 확인 경로로 연결됩니다.",
    whyItMatters: "뉴스 요약보다 원문이 정확하며 정정, 조건, 숫자를 확인할 수 있습니다.",
    beginnerCheck: "정기보고서, 주요사항보고서, 정정공시 여부를 구분합니다.",
    commonMisunderstanding: "DART에 올라온 모든 내용이 즉시 호재나 악재라는 뜻은 아닙니다.",
    scenario: "예: 유상증자 공시는 목적, 할인율, 발행 규모를 먼저 확인해야 합니다.",
    relatedTerms: ["공시", "정정공시", "실적"],
    exampleQuestions: ["DART 공시는 어디를 봐야 해?", "정정공시는 왜 중요해?"]
  }),
  makeTerm({
    id: "daily-candle",
    term: "일봉",
    category: "차트",
    coreSummary: "하루 가격 움직임을 하나의 캔들로 표현한 차트입니다.",
    plainDefinition: "일봉은 하루의 시가, 고가, 저가, 종가를 한 번에 보여줍니다.",
    chartUsage: "단기 매수 검토, 손절 기준, 당일 이벤트 반응을 볼 때 사용합니다.",
    whyItMatters: "초보자가 가장 먼저 익혀야 할 기본 차트 단위입니다.",
    beginnerCheck: "긴 윗꼬리, 거래량 급증, 전저점 이탈을 같이 확인합니다.",
    commonMisunderstanding: "하루 캔들 하나로 추세 전체를 확정하면 위험합니다.",
    scenario: "예: 일봉이 지지선 위에서 반등해도 주봉 추세가 약하면 비중을 줄여 검토합니다.",
    relatedTerms: ["주봉", "월봉", "캔들"],
    exampleQuestions: ["일봉에서 윗꼬리는 어떻게 해석해?", "일봉과 주봉이 다르면 뭘 우선해?"]
  }),
  makeTerm({
    id: "weekly-candle",
    term: "주봉",
    category: "차트",
    coreSummary: "한 주의 가격 흐름을 하나의 캔들로 보는 차트입니다.",
    plainDefinition: "주봉은 일봉보다 큰 흐름을 보여줘 단기 흔들림을 줄여 봅니다.",
    chartUsage: "중기 추세, 지지선, 저항선, 과열 여부를 확인할 때 사용합니다.",
    whyItMatters: "단기 급등락에 흔들리지 않고 큰 방향을 볼 수 있습니다.",
    beginnerCheck: "일봉 매수 신호가 주봉 저항 바로 아래인지 확인합니다.",
    commonMisunderstanding: "주봉이 좋아도 단기 진입 가격이 나쁘면 손실이 커질 수 있습니다.",
    scenario: "예: 일봉 돌파가 나와도 주봉 저항선이 가까우면 추격보다 눌림을 기다립니다.",
    relatedTerms: ["일봉", "월봉", "추세"],
    exampleQuestions: ["주봉은 언제 봐야 해?", "주봉 저항은 왜 중요해?"]
  }),
  makeTerm({
    id: "monthly-candle",
    term: "월봉",
    category: "차트",
    coreSummary: "한 달의 가격 흐름을 하나의 캔들로 보는 장기 차트입니다.",
    plainDefinition: "월봉은 기업과 산업의 큰 사이클을 확인할 때 쓰는 차트입니다.",
    chartUsage: "장기 저항, 큰 추세, 역사적 고점과 저점을 볼 때 사용합니다.",
    whyItMatters: "단기 매매도 장기 위치가 너무 높은지 낮은지 알아야 리스크를 줄일 수 있습니다.",
    beginnerCheck: "월봉상 장기 저항 근처인지, 장기 하락 추세인지 확인합니다.",
    commonMisunderstanding: "월봉이 좋아 보여도 단기 조정은 충분히 나올 수 있습니다.",
    scenario: "예: 월봉 고점 돌파 직후에는 분할 진입과 손절 기준을 더 보수적으로 잡습니다.",
    relatedTerms: ["일봉", "주봉", "저항선"],
    exampleQuestions: ["월봉은 초보자에게 왜 필요해?", "월봉 고점 돌파는 어떻게 봐?"]
  }),
  makeTerm({
    id: "moving-average",
    term: "이동평균선",
    category: "차트",
    coreSummary: "일정 기간 평균 가격을 선으로 이어 추세를 보여줍니다.",
    plainDefinition: "이동평균선은 5일, 20일, 60일처럼 기간별 평균 가격입니다.",
    chartUsage: "차트 위의 20일선, 60일선, 120일선으로 지지와 저항을 봅니다.",
    whyItMatters: "가격이 평균 위에 있는지 아래에 있는지로 추세 강도를 가늠합니다.",
    beginnerCheck: "20일선 회복, 60일선 지지, 거래량 동반 여부를 같이 봅니다.",
    commonMisunderstanding: "선을 넘었다고 자동 매수 신호는 아닙니다.",
    scenario: "예: 20일선을 회복했지만 거래량이 없다면 관망, 거래량이 붙으면 관심 후보로 둡니다.",
    relatedTerms: ["추세", "지지선", "저항선"],
    exampleQuestions: ["20일선은 왜 많이 봐?", "이동평균선 돌파는 매수 신호야?"]
  }),
  makeTerm({
    id: "stop-loss",
    term: "손절",
    category: "매매",
    coreSummary: "손실이 커지기 전에 정한 기준에서 포지션을 줄이는 행동입니다.",
    plainDefinition: "손절은 틀린 판단을 인정하고 손실을 제한하는 리스크 관리입니다.",
    chartUsage: "전저점, 지지선, 이동평균선 이탈 지점을 기준으로 잡습니다.",
    whyItMatters: "좋은 종목을 고르는 것보다 큰 손실을 피하는 것이 오래 살아남는 핵심입니다.",
    beginnerCheck: "매수 전에 손절 가격과 비중을 먼저 정합니다.",
    commonMisunderstanding: "손절은 실패가 아니라 다음 기회를 남기는 규칙입니다.",
    scenario: "예: 20일선 이탈과 하락 거래량 증가가 동시에 나오면 비중 축소를 검토합니다.",
    relatedTerms: ["리스크", "지지선", "분할매수"],
    exampleQuestions: ["손절 기준은 어떻게 잡아?", "손절하면 다시 들어가도 돼?"]
  }),
  makeTerm({
    id: "split-buy",
    term: "분할매수",
    category: "매매",
    coreSummary: "한 번에 사지 않고 여러 가격과 시점으로 나눠 매수하는 방식입니다.",
    plainDefinition: "분할매수는 진입 가격 실수를 줄이기 위해 비중을 나누는 방법입니다.",
    chartUsage: "지지선 1차, 재확인 2차, 돌파 확인 3차처럼 구간을 나눕니다.",
    whyItMatters: "초보자가 확신 하나에 모든 비중을 싣는 위험을 줄입니다.",
    beginnerCheck: "각 구간마다 매수 이유와 중단 조건을 따로 정합니다.",
    commonMisunderstanding: "계속 떨어지는 종목을 무조건 물타기하는 것이 아닙니다.",
    scenario: "예: 지지선 근처 30%, 반등 확인 30%, 저항 돌파 후 40%처럼 조건을 나눕니다.",
    relatedTerms: ["손절", "지지선", "비중"],
    exampleQuestions: ["분할매수와 물타기는 뭐가 달라?", "분할매수 비중은 어떻게 정해?"]
  }),
  makeTerm({
    id: "trend",
    term: "추세",
    category: "차트",
    coreSummary: "가격이 일정 기간 어느 방향으로 움직이는지 나타냅니다.",
    plainDefinition: "추세는 상승, 하락, 횡보처럼 가격의 큰 방향입니다.",
    chartUsage: "고점과 저점의 위치, 이동평균선 기울기, 거래량으로 확인합니다.",
    whyItMatters: "추세와 반대로 매매하면 성공 확률보다 리스크가 커질 수 있습니다.",
    beginnerCheck: "고점과 저점이 함께 높아지는지 먼저 봅니다.",
    commonMisunderstanding: "하루 급등이 바로 상승 추세 전환을 뜻하지 않습니다.",
    scenario: "예: 저점이 높아지고 20일선 위에서 거래량이 붙으면 상승 추세 후보로 봅니다.",
    relatedTerms: ["이동평균선", "지지선", "저항선"],
    exampleQuestions: ["상승 추세는 어떻게 확인해?", "횡보장은 어떻게 대응해?"]
  }),
  makeTerm({
    id: "resistance",
    term: "저항선",
    category: "차트",
    coreSummary: "가격이 오르다가 자주 막히는 구간입니다.",
    plainDefinition: "저항선은 매도 물량이나 부담이 커져 상승이 멈추기 쉬운 가격대입니다.",
    chartUsage: "이전 고점, 거래량이 많았던 가격대, 장기 이동평균선 근처에서 찾습니다.",
    whyItMatters: "매수 검토 시 목표와 리스크를 계산하는 기준이 됩니다.",
    beginnerCheck: "저항선 돌파에 거래량이 붙는지 확인합니다.",
    commonMisunderstanding: "저항선을 한 번 넘었다고 완전히 안전한 것은 아닙니다.",
    scenario: "예: 1차 저항을 돌파했지만 거래량이 약하면 추격보다 재지지를 기다립니다.",
    relatedTerms: ["지지선", "돌파", "거래량"],
    exampleQuestions: ["저항선 돌파는 어떻게 확인해?", "저항선 근처에서는 왜 조심해?"]
  }),
  makeTerm({
    id: "support",
    term: "지지선",
    category: "차트",
    coreSummary: "가격이 내려오다가 자주 버티는 구간입니다.",
    plainDefinition: "지지선은 매수세가 들어와 하락이 멈추기 쉬운 가격대입니다.",
    chartUsage: "이전 저점, 이동평균선, 거래량 밀집 구간에서 확인합니다.",
    whyItMatters: "분할매수 검토와 손절 기준을 세울 때 중요합니다.",
    beginnerCheck: "지지선에서 반등할 때 거래량과 종가 위치를 함께 봅니다.",
    commonMisunderstanding: "지지선은 약속된 바닥이 아니라 깨질 수 있는 기준선입니다.",
    scenario: "예: 지지선 이탈 후 거래량이 늘면 리스크 관리 구간으로 전환합니다.",
    relatedTerms: ["저항선", "손절", "분할매수"],
    exampleQuestions: ["지지선은 어떻게 그어?", "지지선이 깨지면 어떻게 해야 해?"]
  }),
  makeTerm({
    id: "volatility",
    term: "변동성",
    category: "리스크",
    coreSummary: "가격이 흔들리는 폭입니다.",
    plainDefinition: "변동성은 주가가 짧은 기간에 얼마나 크게 움직이는지 나타냅니다.",
    chartUsage: "긴 캔들, 큰 갭, 급격한 거래량 변화, RSI 과열 구간에서 느낄 수 있습니다.",
    whyItMatters: "수익 기회와 손실 가능성이 동시에 커지는 구간을 알려줍니다.",
    beginnerCheck: "변동성이 큰 종목은 비중을 줄이고 손절 기준을 짧게 잡습니다.",
    commonMisunderstanding: "변동성이 크다고 항상 좋은 기회는 아닙니다.",
    scenario: "예: 하루 등락폭이 큰 종목은 관심 후보여도 분할 접근과 관망 조건을 먼저 둡니다.",
    relatedTerms: ["손절", "거래량", "리스크"],
    exampleQuestions: ["변동성이 큰 종목은 어떻게 관리해?", "급등락 종목은 왜 위험해?"]
  }),
  makeTerm({
    id: "trading-halt",
    term: "거래정지",
    category: "리스크",
    coreSummary: "특정 사유로 주식 거래가 일시적으로 멈춘 상태입니다.",
    plainDefinition: "거래정지는 투자자 보호, 중요 공시, 상장폐지 심사 등으로 매매가 제한되는 상황입니다.",
    chartUsage: "차트에 가격 공백이나 거래량 0으로 나타날 수 있습니다.",
    whyItMatters: "원할 때 팔지 못하는 유동성 리스크가 생깁니다.",
    beginnerCheck: "거래정지 사유와 재개 조건을 공시로 확인합니다.",
    commonMisunderstanding: "거래정지가 풀리면 항상 반등한다는 보장은 없습니다.",
    scenario: "예: 거래재개 첫날은 변동성이 매우 커질 수 있어 손실 한도를 먼저 정합니다.",
    relatedTerms: ["공시", "리스크", "유동성"],
    exampleQuestions: ["거래정지는 왜 생겨?", "거래재개 후 무엇을 봐야 해?"]
  }),
  makeTerm({
    id: "market-cap",
    term: "시가총액",
    category: "시장",
    coreSummary: "회사의 주식시장 전체 가치입니다.",
    plainDefinition: "시가총액은 주가에 발행주식 수를 곱한 값입니다.",
    chartUsage: "종목 규모, 대형주/중소형주 구분, 테마 변동성 판단에 씁니다.",
    whyItMatters: "같은 등락률이라도 대형주와 소형주의 의미와 리스크가 다릅니다.",
    beginnerCheck: "시가총액이 작은 종목은 거래대금과 변동성을 더 조심해서 봅니다.",
    commonMisunderstanding: "주가가 낮다고 작은 회사, 주가가 높다고 큰 회사는 아닙니다.",
    scenario: "예: 시총 작은 테마주는 급등 가능성과 급락 리스크가 같이 커집니다.",
    relatedTerms: ["거래대금", "유동성", "대형주"],
    exampleQuestions: ["시가총액과 주가는 뭐가 달라?", "소형주는 왜 변동성이 커?"]
  }),
  makeTerm({
    id: "sector",
    term: "섹터",
    category: "시장",
    coreSummary: "비슷한 산업에 속한 기업 묶음입니다.",
    plainDefinition: "섹터는 반도체, 자동차, 금융처럼 기업을 산업별로 나눈 그룹입니다.",
    chartUsage: "검색, 관심 후보, 시장 브리프에서 같은 방향으로 움직이는 종목군을 봅니다.",
    whyItMatters: "개별 종목 이슈인지 산업 전체 흐름인지 구분할 수 있습니다.",
    beginnerCheck: "내 종목만 오른 것인지 같은 섹터가 함께 오른 것인지 확인합니다.",
    commonMisunderstanding: "같은 섹터라도 실적, 재무, 수급은 종목마다 다릅니다.",
    scenario: "예: 반도체 섹터가 함께 오르면 대표주와 장비주의 강도를 비교합니다.",
    relatedTerms: ["테마", "산업", "수급"],
    exampleQuestions: ["섹터 흐름은 왜 봐야 해?", "섹터와 테마는 뭐가 달라?"]
  }),
  makeTerm({
    id: "theme",
    term: "테마",
    category: "시장",
    coreSummary: "특정 기대나 이슈로 함께 움직이는 종목 묶음입니다.",
    plainDefinition: "테마는 AI, 로봇, 방산처럼 투자자 관심 이슈로 묶인 그룹입니다.",
    chartUsage: "검색 결과, 오늘 관심 후보, 언급량 증가 종목에서 확인합니다.",
    whyItMatters: "단기 수급이 빠르게 몰릴 수 있지만 변동성도 큽니다.",
    beginnerCheck: "테마 이름보다 실제 매출, 공시, 거래대금이 있는지 확인합니다.",
    commonMisunderstanding: "테마에 속한다고 모든 종목이 같은 실적을 내는 것은 아닙니다.",
    scenario: "예: AI 테마 종목은 실제 AI 매출 근거와 단순 기대를 분리해 봅니다.",
    relatedTerms: ["섹터", "수급", "공시"],
    exampleQuestions: ["테마주는 왜 급등락해?", "진짜 테마와 이름만 테마는 어떻게 구분해?"]
  }),
  makeTerm({
    id: "supply-demand",
    term: "수급",
    category: "시장",
    coreSummary: "누가 사고 누가 파는지 보는 자금 흐름입니다.",
    plainDefinition: "수급은 개인, 외국인, 기관 같은 투자 주체의 매수와 매도 흐름입니다.",
    chartUsage: "가격, 거래량, OBV, 투자자별 매매동향과 함께 봅니다.",
    whyItMatters: "가격 움직임이 일시 반응인지 지속 가능한 자금 흐름인지 판단하는 데 도움됩니다.",
    beginnerCheck: "주체별 순매수보다 가격과 거래량이 같은 방향인지 먼저 봅니다.",
    commonMisunderstanding: "외국인 매수라고 무조건 좋은 신호는 아닙니다.",
    scenario: "예: 외국인 매수와 거래량 증가, 20일선 회복이 함께 나오면 관심 후보로 둡니다.",
    relatedTerms: ["거래량", "OBV", "기관"],
    exampleQuestions: ["수급이 좋다는 건 무슨 뜻이야?", "외국인 매수는 왜 중요해?"]
  })
];
