export const COPY = {
  brand: "한국 주식 AI 리서치",
  productTagline: "오늘 시장을 초보자 언어로 읽는 브리프",
  todayBrief: "오늘의 시장 브리프",
  marketBrief: "시장 브리프",
  marketOneLine: "오늘 시장에서 눈에 띄는 종목과 확인할 근거를 먼저 보여줍니다.",
  noMarketOneLine: "아직 저장된 브리프가 없습니다. 최신 요약을 불러오거나 운영 담당자가 생성한 뒤 확인할 수 있습니다.",
  universalSearch: "산업, 테마, 기업, 종목 검색",
  universalSearchPlaceholder: "예: 반도체, 007610, 선도전기, 거래량, DART",
  searchEmpty: "검색 결과가 없습니다. 종목명, 코드, 산업, 테마, 용어를 바꿔 입력해 보세요.",
  aiMarketPanel: "AI 시장 해석",
  aiMarketOneLine: "AI가 오늘 움직인 종목, 차트 신호, 리스크를 한 흐름으로 설명합니다.",
  aiInsight: "AI 인사이트",
  dataAsOf: "데이터 기준일",
  sourceConfidence: "신뢰도",
  beginnerSignals: "초보자가 지금 확인할 신호",
  chartLoading: "차트 불러오는 중...",
  chartFailed: "차트 데이터를 불러오지 못했습니다.",
  riskMode: "판단 성향",
  aggressive: "공격형",
  neutral: "중립형",
  conservative: "보수형",
  chartSummary: "현재 차트 상태 요약",
  buyConditions: "매수 검토 조건",
  splitBuyConditions: "분할매수 검토 조건",
  watchConditions: "관망 조건",
  sellConditions: "매도 검토 조건",
  stopConditions: "손절/리스크 관리 조건",
  oppositeSignals: "반대 신호",
  evidenceData: "근거 데이터",
  analysisDisclaimer: "교육용 분석 보조 정보이며 매수, 매도 지시나 수익 보장이 아닙니다.",
  askChartAi: "AI로 차트 설명",
  aiResearchTitle: "AI 차트 해석",
  portfolioTitle: "포트폴리오 샌드박스",
  portfolioSubtitle: "실계좌 연동 없이 관심 종목과 가상 비중으로 리스크를 봅니다.",
  addToPortfolio: "관심 추가",
  virtualWeight: "가상 비중",
  concentration: "집중도",
  volatility: "변동성",
  openAdmin: "관리자 영역",
  closeAdmin: "관리자 영역 닫기",
  adminTitle: "운영 관리",
  adminSubtitle: "생성, 보관, 일괄 생성은 접힌 패널에서만 실행합니다.",
  selectedDate: "조회 기준일",
  generateToday: "오늘 생성",
  moveToLatest: "최신 요약",
  toggleDarkOn: "다크 모드",
  toggleDarkOff: "라이트 모드",
  prevMonth: "이전",
  nextMonth: "다음",
  generateSelected: "선택일 생성",
  archiveSelected: "보관",
  backfillRun: "일괄 생성",
  loading: "불러오는 중...",
  noSummary: "이 날짜의 요약이 아직 없습니다.",
  marketClosed: "휴장일",
  marketClosedDesc: "이 날짜는 증권시장 휴장일입니다.",
  generatedAt: "생성 시각",
  topGainer: "최대 상승",
  topLoser: "최대 하락",
  mostMentioned: "최다 언급",
  kospiPick: "코스피 픽",
  kosdaqPick: "코스닥 픽",
  rankingBasis: "랭킹 계산 근거",
  rawFirstGainer: "처음 계산 1위 (상승)",
  rawFirstLoser: "처음 계산 1위 (하락)",
  filteredFirstGainer: "검토 후 1위 (상승, 최종)",
  filteredFirstLoser: "검토 후 1위 (하락, 최종)",
  warningNote: "주의 메모",
  code: "종목코드",
  name: "종목명",
  rate: "등락률(%)",
  signals: "감지 신호",
  description: "설명",
  evidenceLinks: "근거 링크",
  verification: "검증",
  date: "날짜",
  result: "결과값",
  directLink: "바로 확인",
  notes: "주의사항",
  showRawNotes: "수집 노트 보기",
  hideRawNotes: "수집 노트 숨기기",
  developerDetails: "검증 상세",
  closeDetails: "상세 닫기",
  summaryExists: "요약 있음",
  gatedHint: "이 화면은 비밀키가 필요합니다. URL에 ?k=비밀키 를 추가하세요.",
  cumulativeSummaries: "누적 요약",
  latestDate: "최신 날짜",
  lastUpdated: "최근 갱신",
  monthlyTotalDays: "월 총 일수",
  monthlyGenerated: "생성 완료",
  monthlyMissing: "미생성",
  monthlyTopMentioned: "월 최다 언급",
  days: ["일", "월", "화", "수", "목", "금", "토"],
  verifyField: "항목",
  verifySource: "출처",
  krxArtifact: "KRX 검증",
  krxPortal: "KRX 포털",
  pykrxRepo: "pykrx 저장소",
  actualCalcDate: "실제 계산일",
  topGainersTitle: "상승 TOP3",
  topLosersTitle: "하락 TOP3",
  mostMentionedTitle: "언급 TOP3",
  postCount: "게시물 수",
  naverDaily: "일별",
  naverMain: "종합",
  naverBoard: "토론",
  learningTitle: "초보자 용어 사전",
  learningSubtitle: "브리프를 읽을 때 막히는 단어를 바로 풀어봅니다.",
  learningSearch: "용어 검색",
  learningSearchPlaceholder: "예: 등락률, PER, 거래량",
  allCategories: "전체",
  coreSummary: "핵심요약",
  whyItMatters: "왜 중요한가",
  beginnerCheck: "먼저 확인할 것",
  caution: "주의할 점",
  scenarioExample: "시나리오 예시",
  relatedTerms: "관련 용어",
  exampleQuestions: "바로 물어보기",
  learningLoadFailed: "용어 사전을 불러오지 못했습니다.",
  noTerms: "검색 결과가 없습니다.",
  assistantTitle: "AI 학습 도우미",
  assistantSubtitle: "오늘 브리프와 용어 사전을 묶어 초보자 관점으로 설명합니다.",
  assistantQuestionLabel: "AI에게 물어볼 질문",
  assistantInputPlaceholder: "궁금한 점을 입력하세요. 예: 거래량이 왜 중요해?",
  assistantAsk: "질문",
  assistantAnswer: "답변",
  confidence: "신뢰도",
  sources: "출처",
  limitations: "한계",
  matchedTerms: "연결된 용어",
  briefTermsTitle: "브리프 읽기 전 확인할 용어",
  historyTitle: "히스토리",
  adminKeyRequired: "운영 기능은 관리자 키가 필요합니다. URL에 ?ak=관리자키 를 추가하면 생성, 보관, 일괄 생성을 사용할 수 있습니다."
};

export const PAGE_LABELS = {
  home: "오늘",
  research: "차트",
  history: "기록",
  learning: "배우기",
  portfolio: "포트폴리오",
  admin: "운영"
};

export const SEARCH_THEME_FALLBACKS = [
  {
    id: "theme-semiconductor",
    type: "theme",
    title: "반도체",
    code: "THEME",
    market: "테마",
    rate: "+2.4%",
    tags: ["AI 반도체", "장비", "소부장"],
    summary: "AI 수요, 설비투자, 환율 변화를 함께 보는 대표 성장 테마입니다."
  },
  {
    id: "theme-battery",
    type: "theme",
    title: "2차전지",
    code: "THEME",
    market: "테마",
    rate: "-1.1%",
    tags: ["소재", "전기차", "수급"],
    summary: "원재료 가격, 전기차 수요, 정책 뉴스가 주가 변동과 자주 연결됩니다."
  },
  {
    id: "industry-finance",
    type: "industry",
    title: "증권/금융",
    code: "IND",
    market: "산업",
    rate: "+0.8%",
    tags: ["금리", "거래대금", "배당"],
    summary: "금리, 증시 거래대금, 배당 기대가 함께 움직이는 산업군입니다."
  }
];
